# Generated by Django 2.1.4 on 2018-12-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=10)),
                ('coin_amount', models.FloatField(default=0.0)),
                ('coin_investment', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.Portfolio'),
        ),
    ]
