# Generated by Django 2.1.4 on 2018-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_auto_20181223_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Crypto portfolio', max_length=50),
        ),
    ]
